basePath: /
definitions:
  models.Address:
    properties:
      created_at:
        type: string
      id:
        type: string
      is_default:
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
      notes:
        type: string
      phone_number:
        type: string
      region:
        allOf:
        - $ref: '#/definitions/models.Region'
        description: Non-persisted field (join-result)
      region_id:
        type: string
      ship_to_name:
        type: string
      street:
        type: string
      user_id:
        type: string
    type: object
  models.Region:
    properties:
      city:
        type: string
      code:
        type: string
      district:
        type: string
      id:
        type: string
      state:
        type: string
      sub_district:
        type: string
      zipcode:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: RESTful API with Gin and MongoDB
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GinAPI
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Masuk sebagai user
      parameters:
      - description: Login Login
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Daftar user baru
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
  /regions:
    get:
      description: Ambil semua region dari database
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      - description: Filter by state
        in: query
        name: state
        type: string
      - description: Filter by city
        in: query
        name: city
        type: string
      - description: Filter by district
        in: query
        name: district
        type: string
      - description: Filter by code
        in: query
        name: code
        type: string
      - description: Filter by zipcode
        in: query
        name: zipcode
        type: string
      - description: Filter by sub_district
        in: query
        name: sub_district
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Region'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all regions
      tags:
      - regions
    post:
      consumes:
      - application/json
      description: Buat region baru
      parameters:
      - description: Region Data
        in: body
        name: region
        required: true
        schema:
          $ref: '#/definitions/models.Region'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create region
      tags:
      - regions
  /regions/{id}:
    delete:
      description: Hapus region berdasarkan ID
      parameters:
      - description: Region ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete region
      tags:
      - regions
    get:
      description: Ambil region berdasarkan ID
      parameters:
      - description: Region ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Region'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get region by ID
      tags:
      - regions
    put:
      consumes:
      - application/json
      description: Update region berdasarkan ID
      parameters:
      - description: Region ID
        in: path
        name: id
        required: true
        type: string
      - description: Region Data
        in: body
        name: region
        required: true
        schema:
          $ref: '#/definitions/models.Region'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update region
      tags:
      - regions
  /users:
    get:
      description: Ambil semua user dari database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Buat user baru
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create user
      tags:
      - users
  /users/addresses:
    get:
      description: Retrieve all addresses associated with a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Address'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get addresses for a user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new address for a user
      parameters:
      - description: Address to create
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Address'
        "400":
          description: Internal Server Error
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new address
      tags:
      - users
  /users/profile:
    get:
      description: Ambil profil user berdasarkan token JWT
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
